# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My downliner
email: jpmouse@free.fr
description: > 
  Searching a downline for some online programs.
  
# the subpath of your site, e.g. /blog
baseurl: "" 
# the base hostname & protocol for your site
url: "http://mydownliner.github.io" 
#twitter_username: jekyllrb
github_username:  mydownliner

# Build settings
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
exclude: [vendor] # Excluded from travis-ci build
markdown: kramdown
